from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from PIL import Image

from .alpha import normalize_alpha
from .asset import trim_transparent
from .background import remove_flat_background
from .palette import load_hex_palette, map_to_palette, quantize_colors, select_project_palette
from .recovery import RecoveryInfo, recover_auto, recover_manual_scale, recover_manual_size
from .validation import ValidationReport, validate_asset


@dataclass
class ProcessOptions:
    auto_grid: bool = True
    scale_x: int = 1
    scale_y: int = 1
    target_width: int | None = None
    target_height: int | None = None
    max_colors: int = 24
    remove_background: bool = False
    background_tolerance: float = 24.0
    palette_path: str | None = None
    binary_alpha: bool = True
    alpha_threshold: int = 128
    trim_transparent: bool = True
    trim_padding: int = 1
    recovery_mode: str = "full"


@dataclass
class ProcessResult:
    image: Image.Image
    grid: RecoveryInfo
    report: ValidationReport


class AssetPipeline:
    def process(self, image: Image.Image, options: ProcessOptions) -> ProcessResult:
        work = image.convert("RGBA")

        if options.remove_background:
            work = remove_flat_background(work, tolerance=options.background_tolerance)

        if options.target_width and options.target_height:
            work, grid = recover_manual_size(work, options.target_width, options.target_height)
        elif options.auto_grid:
            work, grid = recover_auto(work, mode=options.recovery_mode)
        else:
            work, grid = recover_manual_scale(work, options.scale_x, options.scale_y)

        if options.binary_alpha:
            work = normalize_alpha(work, threshold=options.alpha_threshold)

        if options.palette_path:
            palette = load_hex_palette(Path(options.palette_path))
            selected = select_project_palette(work, palette, max_colors=options.max_colors)
            work = map_to_palette(work, selected)
        else:
            work = quantize_colors(work, max_colors=options.max_colors)

        # A transparent source generated by an image model often contains a huge
        # empty canvas. Crop only after native-grid reconstruction so trimming
        # cannot disturb the pseudo-pixel lattice used by the detector.
        if options.trim_transparent and not (options.target_width and options.target_height):
            work = trim_transparent(work, alpha_threshold=1, padding=options.trim_padding)

        report = validate_asset(work)
        return ProcessResult(image=work, grid=grid, report=report)
